// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Campanha struct {
	ID          uuid.UUID      `json:"id"`
	Nome        string         `json:"nome"`
	Imagem      sql.NullString `json:"imagem"`
	DataInicio  sql.NullTime   `json:"data_inicio"`
	DataFim     sql.NullTime   `json:"data_fim"`
	Equipe      sql.NullString `json:"equipe"`
	Localizacao interface{}    `json:"localizacao"`
	Objetivos   sql.NullString `json:"objetivos"`
	Contato     sql.NullString `json:"contato"`
	Status      sql.NullString `json:"status"`
	Notas       sql.NullString `json:"notas"`
	Descricao   sql.NullString `json:"descricao"`
}

type CampanhaEquipamento struct {
	ID            uuid.UUID `json:"id"`
	CampanhaID    uuid.UUID `json:"campanha_id"`
	EquipamentoID uuid.UUID `json:"equipamento_id"`
}

type Equipamento struct {
	ID                    uuid.UUID       `json:"id"`
	Nome                  string          `json:"nome"`
	Descricao             sql.NullString  `json:"descricao"`
	Tipo                  sql.NullString  `json:"tipo"`
	NumeroSerie           sql.NullString  `json:"numero_serie"`
	Modelo                sql.NullString  `json:"modelo"`
	Fabricante            sql.NullString  `json:"fabricante"`
	Frequencia            sql.NullFloat64 `json:"frequencia"`
	DataCalibracao        sql.NullTime    `json:"data_calibracao"`
	DataUltimaManutencao  sql.NullTime    `json:"data_ultima_manutencao"`
	ResponsavelManutencao sql.NullString  `json:"responsavel_manutencao"`
	DataFabricacao        sql.NullTime    `json:"data_fabricacao"`
	DataAquisicao         sql.NullTime    `json:"data_aquisicao"`
	TiposDados            sql.NullString  `json:"tipos_dados"`
	Notas                 sql.NullString  `json:"notas"`
	DataExpiracaoGarantia sql.NullTime    `json:"data_expiracao_garantia"`
	StatusOperacional     sql.NullString  `json:"status_operacional"`
	Localizacao           interface{}     `json:"localizacao"`
	Imagem                sql.NullString  `json:"imagem"`
}

type LidarWindcubeDado struct {
	ID                  int32           `json:"id"`
	CampanhaID          uuid.UUID       `json:"campanha_id"`
	EquipamentoID       uuid.UUID       `json:"equipamento_id"`
	Timestamp           time.Time       `json:"timestamp"`
	Posicao             sql.NullString  `json:"posicao"`
	Temperatura         sql.NullFloat64 `json:"temperatura"`
	WiperCount          sql.NullInt32   `json:"wiper_count"`
	Cnr40m              sql.NullFloat64 `json:"cnr_40m"`
	RadialWindSpeed40m  sql.NullFloat64 `json:"radial_wind_speed_40m"`
	WindSpeedDisp40m    sql.NullFloat64 `json:"wind_speed_disp_40m"`
	WindSpeed40m        sql.NullFloat64 `json:"wind_speed_40m"`
	WindDirection40m    sql.NullFloat64 `json:"wind_direction_40m"`
	XWind40m            sql.NullFloat64 `json:"x_wind_40m"`
	YWind40m            sql.NullFloat64 `json:"y_wind_40m"`
	ZWind40m            sql.NullFloat64 `json:"z_wind_40m"`
	Cnr50m              sql.NullFloat64 `json:"cnr_50m"`
	RadialWindSpeed50m  sql.NullFloat64 `json:"radial_wind_speed_50m"`
	WindSpeedDisp50m    sql.NullFloat64 `json:"wind_speed_disp_50m"`
	WindSpeed50m        sql.NullFloat64 `json:"wind_speed_50m"`
	WindDirection50m    sql.NullFloat64 `json:"wind_direction_50m"`
	XWind50m            sql.NullFloat64 `json:"x_wind_50m"`
	YWind50m            sql.NullFloat64 `json:"y_wind_50m"`
	ZWind50m            sql.NullFloat64 `json:"z_wind_50m"`
	Cnr60m              sql.NullFloat64 `json:"cnr_60m"`
	RadialWindSpeed60m  sql.NullFloat64 `json:"radial_wind_speed_60m"`
	WindSpeedDisp60m    sql.NullFloat64 `json:"wind_speed_disp_60m"`
	WindSpeed60m        sql.NullFloat64 `json:"wind_speed_60m"`
	WindDirection60m    sql.NullFloat64 `json:"wind_direction_60m"`
	XWind60m            sql.NullFloat64 `json:"x_wind_60m"`
	YWind60m            sql.NullFloat64 `json:"y_wind_60m"`
	ZWind60m            sql.NullFloat64 `json:"z_wind_60m"`
	Cnr70m              sql.NullFloat64 `json:"cnr_70m"`
	RadialWindSpeed70m  sql.NullFloat64 `json:"radial_wind_speed_70m"`
	WindSpeedDisp70m    sql.NullFloat64 `json:"wind_speed_disp_70m"`
	WindSpeed70m        sql.NullFloat64 `json:"wind_speed_70m"`
	WindDirection70m    sql.NullFloat64 `json:"wind_direction_70m"`
	XWind70m            sql.NullFloat64 `json:"x_wind_70m"`
	YWind70m            sql.NullFloat64 `json:"y_wind_70m"`
	ZWind70m            sql.NullFloat64 `json:"z_wind_70m"`
	Cnr80m              sql.NullFloat64 `json:"cnr_80m"`
	RadialWindSpeed80m  sql.NullFloat64 `json:"radial_wind_speed_80m"`
	WindSpeedDisp80m    sql.NullFloat64 `json:"wind_speed_disp_80m"`
	WindSpeed80m        sql.NullFloat64 `json:"wind_speed_80m"`
	WindDirection80m    sql.NullFloat64 `json:"wind_direction_80m"`
	XWind80m            sql.NullFloat64 `json:"x_wind_80m"`
	YWind80m            sql.NullFloat64 `json:"y_wind_80m"`
	ZWind80m            sql.NullFloat64 `json:"z_wind_80m"`
	Cnr90m              sql.NullFloat64 `json:"cnr_90m"`
	RadialWindSpeed90m  sql.NullFloat64 `json:"radial_wind_speed_90m"`
	WindSpeedDisp90m    sql.NullFloat64 `json:"wind_speed_disp_90m"`
	WindSpeed90m        sql.NullFloat64 `json:"wind_speed_90m"`
	WindDirection90m    sql.NullFloat64 `json:"wind_direction_90m"`
	XWind90m            sql.NullFloat64 `json:"x_wind_90m"`
	YWind90m            sql.NullFloat64 `json:"y_wind_90m"`
	ZWind90m            sql.NullFloat64 `json:"z_wind_90m"`
	Cnr100m             sql.NullFloat64 `json:"cnr_100m"`
	RadialWindSpeed100m sql.NullFloat64 `json:"radial_wind_speed_100m"`
	WindSpeedDisp100m   sql.NullFloat64 `json:"wind_speed_disp_100m"`
	WindSpeed100m       sql.NullFloat64 `json:"wind_speed_100m"`
	WindDirection100m   sql.NullFloat64 `json:"wind_direction_100m"`
	XWind100m           sql.NullFloat64 `json:"x_wind_100m"`
	YWind100m           sql.NullFloat64 `json:"y_wind_100m"`
	ZWind100m           sql.NullFloat64 `json:"z_wind_100m"`
	Cnr110m             sql.NullFloat64 `json:"cnr_110m"`
	RadialWindSpeed110m sql.NullFloat64 `json:"radial_wind_speed_110m"`
	WindSpeedDisp110m   sql.NullFloat64 `json:"wind_speed_disp_110m"`
	WindSpeed110m       sql.NullFloat64 `json:"wind_speed_110m"`
	WindDirection110m   sql.NullFloat64 `json:"wind_direction_110m"`
	XWind110m           sql.NullFloat64 `json:"x_wind_110m"`
	YWind110m           sql.NullFloat64 `json:"y_wind_110m"`
	ZWind110m           sql.NullFloat64 `json:"z_wind_110m"`
	Cnr120m             sql.NullFloat64 `json:"cnr_120m"`
	RadialWindSpeed120m sql.NullFloat64 `json:"radial_wind_speed_120m"`
	WindSpeedDisp120m   sql.NullFloat64 `json:"wind_speed_disp_120m"`
	WindSpeed120m       sql.NullFloat64 `json:"wind_speed_120m"`
	WindDirection120m   sql.NullFloat64 `json:"wind_direction_120m"`
	XWind120m           sql.NullFloat64 `json:"x_wind_120m"`
	YWind120m           sql.NullFloat64 `json:"y_wind_120m"`
	ZWind120m           sql.NullFloat64 `json:"z_wind_120m"`
	Cnr130m             sql.NullFloat64 `json:"cnr_130m"`
	RadialWindSpeed130m sql.NullFloat64 `json:"radial_wind_speed_130m"`
	WindSpeedDisp130m   sql.NullFloat64 `json:"wind_speed_disp_130m"`
	WindSpeed130m       sql.NullFloat64 `json:"wind_speed_130m"`
	WindDirection130m   sql.NullFloat64 `json:"wind_direction_130m"`
	XWind130m           sql.NullFloat64 `json:"x_wind_130m"`
	YWind130m           sql.NullFloat64 `json:"y_wind_130m"`
	ZWind130m           sql.NullFloat64 `json:"z_wind_130m"`
	Cnr140m             sql.NullFloat64 `json:"cnr_140m"`
	RadialWindSpeed140m sql.NullFloat64 `json:"radial_wind_speed_140m"`
	WindSpeedDisp140m   sql.NullFloat64 `json:"wind_speed_disp_140m"`
	WindSpeed140m       sql.NullFloat64 `json:"wind_speed_140m"`
	WindDirection140m   sql.NullFloat64 `json:"wind_direction_140m"`
	XWind140m           sql.NullFloat64 `json:"x_wind_140m"`
	YWind140m           sql.NullFloat64 `json:"y_wind_140m"`
	ZWind140m           sql.NullFloat64 `json:"z_wind_140m"`
	Cnr150m             sql.NullFloat64 `json:"cnr_150m"`
	RadialWindSpeed150m sql.NullFloat64 `json:"radial_wind_speed_150m"`
	WindSpeedDisp150m   sql.NullFloat64 `json:"wind_speed_disp_150m"`
	WindSpeed150m       sql.NullFloat64 `json:"wind_speed_150m"`
	WindDirection150m   sql.NullFloat64 `json:"wind_direction_150m"`
	XWind150m           sql.NullFloat64 `json:"x_wind_150m"`
	YWind150m           sql.NullFloat64 `json:"y_wind_150m"`
	ZWind150m           sql.NullFloat64 `json:"z_wind_150m"`
	Cnr160m             sql.NullFloat64 `json:"cnr_160m"`
	RadialWindSpeed160m sql.NullFloat64 `json:"radial_wind_speed_160m"`
	WindSpeedDisp160m   sql.NullFloat64 `json:"wind_speed_disp_160m"`
	WindSpeed160m       sql.NullFloat64 `json:"wind_speed_160m"`
	WindDirection160m   sql.NullFloat64 `json:"wind_direction_160m"`
	XWind160m           sql.NullFloat64 `json:"x_wind_160m"`
	YWind160m           sql.NullFloat64 `json:"y_wind_160m"`
	ZWind160m           sql.NullFloat64 `json:"z_wind_160m"`
	Cnr170m             sql.NullFloat64 `json:"cnr_170m"`
	RadialWindSpeed170m sql.NullFloat64 `json:"radial_wind_speed_170m"`
	WindSpeedDisp170m   sql.NullFloat64 `json:"wind_speed_disp_170m"`
	WindSpeed170m       sql.NullFloat64 `json:"wind_speed_170m"`
	WindDirection170m   sql.NullFloat64 `json:"wind_direction_170m"`
	XWind170m           sql.NullFloat64 `json:"x_wind_170m"`
	YWind170m           sql.NullFloat64 `json:"y_wind_170m"`
	ZWind170m           sql.NullFloat64 `json:"z_wind_170m"`
	Cnr180m             sql.NullFloat64 `json:"cnr_180m"`
	RadialWindSpeed180m sql.NullFloat64 `json:"radial_wind_speed_180m"`
	WindSpeedDisp180m   sql.NullFloat64 `json:"wind_speed_disp_180m"`
	WindSpeed180m       sql.NullFloat64 `json:"wind_speed_180m"`
	WindDirection180m   sql.NullFloat64 `json:"wind_direction_180m"`
	XWind180m           sql.NullFloat64 `json:"x_wind_180m"`
	YWind180m           sql.NullFloat64 `json:"y_wind_180m"`
	ZWind180m           sql.NullFloat64 `json:"z_wind_180m"`
	Cnr190m             sql.NullFloat64 `json:"cnr_190m"`
	RadialWindSpeed190m sql.NullFloat64 `json:"radial_wind_speed_190m"`
	WindSpeedDisp190m   sql.NullFloat64 `json:"wind_speed_disp_190m"`
	WindSpeed190m       sql.NullFloat64 `json:"wind_speed_190m"`
	WindDirection190m   sql.NullFloat64 `json:"wind_direction_190m"`
	XWind190m           sql.NullFloat64 `json:"x_wind_190m"`
	YWind190m           sql.NullFloat64 `json:"y_wind_190m"`
	ZWind190m           sql.NullFloat64 `json:"z_wind_190m"`
	Cnr200m             sql.NullFloat64 `json:"cnr_200m"`
	RadialWindSpeed200m sql.NullFloat64 `json:"radial_wind_speed_200m"`
	WindSpeedDisp200m   sql.NullFloat64 `json:"wind_speed_disp_200m"`
	WindSpeed200m       sql.NullFloat64 `json:"wind_speed_200m"`
	WindDirection200m   sql.NullFloat64 `json:"wind_direction_200m"`
	XWind200m           sql.NullFloat64 `json:"x_wind_200m"`
	YWind200m           sql.NullFloat64 `json:"y_wind_200m"`
	ZWind200m           sql.NullFloat64 `json:"z_wind_200m"`
	Cnr220m             sql.NullFloat64 `json:"cnr_220m"`
	RadialWindSpeed220m sql.NullFloat64 `json:"radial_wind_speed_220m"`
	WindSpeedDisp220m   sql.NullFloat64 `json:"wind_speed_disp_220m"`
	WindSpeed220m       sql.NullFloat64 `json:"wind_speed_220m"`
	WindDirection220m   sql.NullFloat64 `json:"wind_direction_220m"`
	XWind220m           sql.NullFloat64 `json:"x_wind_220m"`
	YWind220m           sql.NullFloat64 `json:"y_wind_220m"`
	ZWind220m           sql.NullFloat64 `json:"z_wind_220m"`
	Cnr250m             sql.NullFloat64 `json:"cnr_250m"`
	RadialWindSpeed250m sql.NullFloat64 `json:"radial_wind_speed_250m"`
	WindSpeedDisp250m   sql.NullFloat64 `json:"wind_speed_disp_250m"`
	WindSpeed250m       sql.NullFloat64 `json:"wind_speed_250m"`
	WindDirection250m   sql.NullFloat64 `json:"wind_direction_250m"`
	XWind250m           sql.NullFloat64 `json:"x_wind_250m"`
	YWind250m           sql.NullFloat64 `json:"y_wind_250m"`
	ZWind250m           sql.NullFloat64 `json:"z_wind_250m"`
	Cnr300m             sql.NullFloat64 `json:"cnr_300m"`
	RadialWindSpeed300m sql.NullFloat64 `json:"radial_wind_speed_300m"`
	WindSpeedDisp300m   sql.NullFloat64 `json:"wind_speed_disp_300m"`
	WindSpeed300m       sql.NullFloat64 `json:"wind_speed_300m"`
	WindDirection300m   sql.NullFloat64 `json:"wind_direction_300m"`
	XWind300m           sql.NullFloat64 `json:"x_wind_300m"`
	YWind300m           sql.NullFloat64 `json:"y_wind_300m"`
	ZWind300m           sql.NullFloat64 `json:"z_wind_300m"`
}
